const { test } = require('@playwright/test');
const { Login } = require('../../login');
const { Global, Basics, Acties } = require('../../objects')

test('Buttons check', async ({ page, browser }) => {
//   page.on('dialog', dialog => dialog.accept());
  const context = await browser.newContext()
  await page.goto(Global.url)

  await Login(page, "tjitske@djurve.nl")

  await page.click(Acties.Buttons.a_listRegistraties)
  await page.locator(Acties.Buttons.button_add).hover()
  await page.click(Acties.Buttons.span_Disturbance)
  await page.fill(Acties.Buttons.input_Titel_name, "Koffiemachine is kapot")
  await page.fill(Basics['Comment-Description'], "Dit is erg vervelend!")
  await page.selectOption(Acties.Buttons['select_-- Selecteer team of player --Alien _db9ad7'], "41ca13be-83bc-0004-8bd1-454f215dd1a3")
  await page.selectOption(Acties.selectLocation, "00000000-0000-0000-0000-000000000000")
  await page.click(Acties.Buttons.button_Opslaan)
  await page.waitForTimeout(1000)
  await page.locator(Basics.ProgressBar).first().waitFor({state: 'hidden'})
  await page.click(Acties.Buttons['button_Opslaan  actie'])
  await page.locator(Basics.ProgressBar).first().waitFor({state: 'hidden'})
  await page.fill(Basics['Message-Description'], "Kun jij dit repareren?")
  await page.selectOption(Acties.Buttons['select_-- Selecteer team --Agullas Mengen M_2b7149'], "41ca13be-83bc-0032-8bd1-454f215dd1a3")
  await page.click(Acties.Buttons.button_Verzenden)
  await page.locator(Basics.ProgressBar).first().waitFor({state: 'hidden'})
  await page.click(Acties.Buttons.button_Accepteren)
  await page.click(Acties.Buttons.button_Annuleren)
  await page.click(Acties.Buttons.button_Weigeren)
  await page.click(Acties.Buttons.button_Annuleren)
  await page.click(Acties.Buttons.button_Doorsturen)
  await page.click(Acties.Buttons.button_Annuleren_1)
  await page.click(Acties.Buttons.button_Terugtrekken)
  await page.click(Acties.Buttons.button_Annuleren)
  await page.waitForTimeout(1000)
  await page.click(Acties.Buttons.i_edit)
  await page.locator(Basics.ProgressBar).first().waitFor({state: 'hidden'})
  await page.waitForTimeout(1000)
  await page.click(Acties.Buttons.button_Terug)
  await page.click(Acties.Buttons.i_message)
  await page.click(Acties.Buttons.button_Annuleren)
  await page.click(Acties.Buttons.i_share)
  await page.click("#show-filters-x")
  await page.click(Acties.Buttons.button_Terug)
  await page.click(Acties.Acties.li_first_action)
  await page.click(Acties.Buttons.i_edit)
  await page.locator(Basics.ProgressBar).first().waitFor({state: 'hidden'})
  await page.click(Acties.Buttons.button_Terug)
  await page.click(Acties.Buttons.button_Afsluiten)
  await page.click(Acties.Buttons.button_Annuleren)
  await page.click(Acties.Buttons.i_share)

  await context.close()
});